from dotenv import load_dotenv
import os

load_dotenv()

UPLOAD_SERVICE_SECRET = os.getenv("UPLOAD_SERVICE_SECRET")
UPLOAD_SERVICE_API_URL = os.getenv("UPLOAD_SERVICE_API_URL")
UPLOAD_SERVICE_API_KEY = os.getenv("UPLOAD_SERVICE_API_KEY")
UPLOAD_SERVICE_LOG_FILE = os.getenv("UPLOAD_SERVICE_LOG_FILE")
UPLOAD_SERVICE_DEBUG_LOGS = os.getenv("UPLOAD_SERVICE_DEBUG_LOGS")
UPLOADS_FOLDER = os.getenv("UPLOADS_FOLDER")
UPLOAD_QUEUE_SERVICE_URL = os.getenv("UPLOAD_QUEUE_SERVICE_URL")
UPLOAD_QUEUE_SERVICE_API_KEY = os.getenv("UPLOAD_QUEUE_SERVICE_API_KEY")
